// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"saga/order/internal/logic"
	"saga/order/internal/svc"
	"saga/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Create(ctx context.Context, in *order.CreateRequest) (*order.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *OrderServer) CreateRevert(ctx context.Context, in *order.CreateRequest) (*order.CreateResponse, error) {
	l := logic.NewCreateRevertLogic(ctx, s.svcCtx)
	return l.CreateRevert(in)
}
